export const scanData = [
  {
    id: 1,
    name: "Web App Servers",
    type: "Greybox",
    status: "Completed",
    progress: 100,
    vulnerabilities: { critical: 5, high: 12, medium: 23, low: 18 },
    lastScan: "4d ago",
  },
  {
    id: 2,
    name: "Web App Servers",
    type: "Greybox",
    status: "Completed",
    progress: 100,
    vulnerabilities: { critical: 5, high: 12, medium: 23, low: 18 },
    lastScan: "4d ago",
  },
  {
    id: 3,
    name: "Web App Servers",
    type: "Greybox",
    status: "Completed",
    progress: 100,
    vulnerabilities: { critical: 5, high: 12, medium: 23, low: 18 },
    lastScan: "4d ago",
  },
  {
    id: 4,
    name: "Web App Servers",
    type: "Greybox",
    status: "Completed",
    progress: 100,
    vulnerabilities: { critical: 5, high: 12, medium: 23, low: 18 },
    lastScan: "4d ago",
  },
  {
    id: 5,
    name: "Web App Servers",
    type: "Greybox",
    status: "Completed",
    progress: 100,
    vulnerabilities: { critical: 5, high: 12, medium: 23, low: 18 },
    lastScan: "4d ago",
  },
  {
    id: 6,
    name: "Web App Servers",
    type: "Greybox",
    status: "Scheduled",
    progress: 100,
    vulnerabilities: { critical: 5, high: 12, medium: 0, low: 0 },
    lastScan: "4d ago",
  },
  {
    id: 7,
    name: "Web App Servers",
    type: "Greybox",
    status: "Scheduled",
    progress: 100,
    vulnerabilities: { critical: 5, high: 12, medium: 0, low: 0 },
    lastScan: "4d ago",
  },
  {
    id: 8,
    name: "IoT Devices",
    type: "Blackbox",
    status: "Failed",
    progress: 10,
    vulnerabilities: { critical: 2, high: 4, medium: 8, low: 1 },
    lastScan: "3d ago",
  },
  {
    id: 9,
    name: "Temp Data",
    type: "Blackbox",
    status: "Failed",
    progress: 10,
    vulnerabilities: { critical: 2, high: 4, medium: 8, low: 1 },
    lastScan: "3d ago",
  },
  {
    id: 10,
    name: "Payment Gateway",
    type: "Greybox",
    status: "Completed",
    progress: 100,
    vulnerabilities: { critical: 1, high: 3, medium: 10, low: 22 },
    lastScan: "1d ago",
  },
  {
    id: 11,
    name: "Internal API",
    type: "Greybox",
    status: "Completed",
    progress: 100,
    vulnerabilities: { critical: 0, high: 2, medium: 6, low: 14 },
    lastScan: "2d ago",
  },
  {
    id: 12,
    name: "Admin Panel",
    type: "Greybox",
    status: "Scheduled",
    progress: 65,
    vulnerabilities: { critical: 3, high: 6, medium: 12, low: 9 },
    lastScan: "5h ago",
  },
  {
    id: 13,
    name: "Cloud Infrastructure",
    type: "Blackbox",
    status: "Completed",
    progress: 100,
    vulnerabilities: { critical: 7, high: 15, medium: 30, low: 25 },
    lastScan: "6d ago",
  },
];
